// <auto-generated />
using Eshop.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eshop.Api.Migrations
{
    [DbContext(typeof(EshopDbContext))]
    partial class EshopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eshop.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hlasový asistent Siri – v angličtine, kompatibilná aplikácia Apple Home, podpora iOS, pripojenie cez WiFi 2,4 GHz a bluetooth, otvorený systém, fungovanie samostatne, ovládanie domácnosti, kamera, 2 mikrofóny na snímanie okolitého zvuku, podporuje Apple Music, basový reproduktor",
                            ImgUri = "https://image.alza.cz/products/JA041a1/JA041a1.jpg?width=500&height=500",
                            Name = "Apple HomePod mini biely",
                            Price = 125.9m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hlasový asistent Amazon Alexa – kompatibilný s aplikáciami výrobcu, podpora Android a iOS, pripojenie cez WiFi 2,4 GHz, otvorený systém, fungovanie samostatne, ovládanie domácnosti, tvorba scenárov, displej, hodiny a tlačidlo na odpojenie mikrofónu, dotykové ovládanie",
                            ImgUri = "https://image.alza.cz/products/AME1047/AME1047.jpg?width=500&height=500",
                            Name = "Amazon Echo Spot Glacier White",
                            Price = 83.9m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hlasový asistent Google Assistant – v angličtine, kompatibilná aplikácia google Home, podpora Android a iOS, pripojenie cez WiFi 2,4 GHz a bluetooth, otvorený systém, fungovanie samostatne, ovládanie domácnosti, 3 mikrofóny na snímanie okolitého zvuku, podporuje Spotify, basový a výškový reproduktor",
                            ImgUri = "https://image.alza.cz/products/GOOGnestA1/GOOGnestA1.jpg?width=500&height=500",
                            Name = "Google Nest Audio Chalk",
                            Price = 92.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
