@Eshop_Api_HostAddress = http://localhost:5038

GET {{Eshop_Api_HostAddress}}/api/v1/products
Accept: application/json
###
GET {{Eshop_Api_HostAddress}}/api/v1/products/1
Accept: application/json
###
PATCH {{Eshop_Api_HostAddress}}/api/v1/products/1/description
Accept: application/json
Content-Type: application/json

{
  "description": "Updated product description"
}
###
GET {{Eshop_Api_HostAddress}}/api/v2/products?pageNumber=1&pageSize=2
Accept: application/json
